"""Public API for DWARF experiment configuration, discovery and datasets."""

from dwarf.pipeline.artifacts import (
    ExtractedWatermark,
    ImageArtifact,
    OriginalWatermark,
)
from dwarf.pipeline.catalog import SolutionCatalog
from dwarf.pipeline.config import (
    SCHEMA_VERSION,
    ArtifactReference,
    AttackScenarioSpec,
    AttackStepSpec,
    DirectoryDatasetSpec,
    EmbeddingSpec,
    ExecutionSpec,
    ExperimentConfig,
    ExperimentMetadata,
    FixedBitsWatermarkSpec,
    ImagePreprocessingSpec,
    MetricBindingSpec,
    OperationSpec,
    OutputSpec,
    ParameterSpace,
    RandomBitsWatermarkSpec,
    ReportSpec,
    WatermarkSpec,
)
from dwarf.pipeline.config_loader import load_experiment_config
from dwarf.pipeline.datasets import DirectoryDatasetSource
from dwarf.pipeline.exceptions import (
    ArtifactValidationError,
    ConfigLoadError,
    DatasetDiscoveryError,
    DatasetIntegrityError,
    DatasetLoadError,
    DatasetManifestError,
    DatasetSourceError,
    SemanticValidationError,
    SemanticValidationIssue,
    SolutionCatalogError,
    SolutionConflictError,
    SolutionDiscoveryError,
)
from dwarf.pipeline.manifest import (
    MANIFEST_SCHEMA_VERSION,
    DatasetManifest,
    SampleReference,
    make_sample_id,
)
from dwarf.pipeline.resolved import (
    ResolvedAttackScenario,
    ResolvedAttackStep,
    ResolvedEmbedding,
    ResolvedExperiment,
    ResolvedMetric,
)
from dwarf.pipeline.solution_spec import (
    UNSET,
    ArtifactInputSpec,
    ArtifactKind,
    DataContract,
    ParameterKind,
    ParameterLinkSpec,
    ParameterSpec,
    SolutionKind,
    SolutionSpec,
)
from dwarf.pipeline.solution_spec import (
    OperationSpec as SolutionOperationSpec,
)

__all__ = [
    "MANIFEST_SCHEMA_VERSION",
    "SCHEMA_VERSION",
    "UNSET",
    "ArtifactInputSpec",
    "ArtifactKind",
    "ArtifactReference",
    "ArtifactValidationError",
    "AttackScenarioSpec",
    "AttackStepSpec",
    "ConfigLoadError",
    "DataContract",
    "DatasetDiscoveryError",
    "DatasetIntegrityError",
    "DatasetLoadError",
    "DatasetManifest",
    "DatasetManifestError",
    "DatasetSourceError",
    "DirectoryDatasetSource",
    "DirectoryDatasetSpec",
    "EmbeddingSpec",
    "ExecutionSpec",
    "ExperimentConfig",
    "ExperimentMetadata",
    "ExtractedWatermark",
    "FixedBitsWatermarkSpec",
    "ImageArtifact",
    "ImagePreprocessingSpec",
    "MetricBindingSpec",
    "OperationSpec",
    "OriginalWatermark",
    "OutputSpec",
    "ParameterKind",
    "ParameterLinkSpec",
    "ParameterSpace",
    "ParameterSpec",
    "RandomBitsWatermarkSpec",
    "ReportSpec",
    "ResolvedAttackScenario",
    "ResolvedAttackStep",
    "ResolvedEmbedding",
    "ResolvedExperiment",
    "ResolvedMetric",
    "SampleReference",
    "SemanticValidationError",
    "SemanticValidationIssue",
    "SolutionCatalog",
    "SolutionCatalogError",
    "SolutionConflictError",
    "SolutionDiscoveryError",
    "SolutionKind",
    "SolutionOperationSpec",
    "SolutionSpec",
    "WatermarkSpec",
    "load_experiment_config",
    "make_sample_id",
]
