"""Public configuration and solution-catalog API for the DWARF pipeline."""

from dwarf.pipeline.catalog import SolutionCatalog
from dwarf.pipeline.config import (
    SCHEMA_VERSION,
    ArtifactReference,
    AttackScenarioSpec,
    AttackStepSpec,
    DirectoryDatasetSpec,
    EmbeddingSpec,
    ExecutionSpec,
    ExperimentConfig,
    ExperimentMetadata,
    FixedBitsWatermarkSpec,
    ImagePreprocessingSpec,
    MetricBindingSpec,
    OperationSpec,
    OutputSpec,
    ParameterSpace,
    RandomBitsWatermarkSpec,
    ReportSpec,
    WatermarkSpec,
)
from dwarf.pipeline.config_loader import load_experiment_config
from dwarf.pipeline.exceptions import (
    ConfigLoadError,
    SemanticValidationError,
    SemanticValidationIssue,
    SolutionCatalogError,
    SolutionConflictError,
    SolutionDiscoveryError,
)
from dwarf.pipeline.resolved import (
    ResolvedAttackScenario,
    ResolvedAttackStep,
    ResolvedEmbedding,
    ResolvedExperiment,
    ResolvedMetric,
)
from dwarf.pipeline.solution_spec import (
    UNSET,
    ArtifactInputSpec,
    ArtifactKind,
    DataContract,
    ParameterKind,
    ParameterLinkSpec,
    ParameterSpec,
    SolutionKind,
    SolutionSpec,
)
from dwarf.pipeline.solution_spec import (
    OperationSpec as SolutionOperationSpec,
)

__all__ = [
    "SCHEMA_VERSION",
    "UNSET",
    "ArtifactInputSpec",
    "ArtifactKind",
    "ArtifactReference",
    "AttackScenarioSpec",
    "AttackStepSpec",
    "ConfigLoadError",
    "DataContract",
    "DirectoryDatasetSpec",
    "EmbeddingSpec",
    "ExecutionSpec",
    "ExperimentConfig",
    "ExperimentMetadata",
    "FixedBitsWatermarkSpec",
    "ImagePreprocessingSpec",
    "MetricBindingSpec",
    "OperationSpec",
    "OutputSpec",
    "SolutionOperationSpec",
    "ParameterKind",
    "ParameterLinkSpec",
    "ParameterSpace",
    "ParameterSpec",
    "RandomBitsWatermarkSpec",
    "ReportSpec",
    "ResolvedAttackScenario",
    "ResolvedAttackStep",
    "ResolvedEmbedding",
    "ResolvedExperiment",
    "ResolvedMetric",
    "SemanticValidationError",
    "SemanticValidationIssue",
    "SolutionCatalog",
    "SolutionCatalogError",
    "SolutionConflictError",
    "SolutionDiscoveryError",
    "SolutionKind",
    "SolutionSpec",
    "WatermarkSpec",
    "load_experiment_config",
]
