import numpy as np

from PIL import Image, ImageEnhance, ImageOps
from dwarf.core.embedding_orchestrator.embedding_core import Ready_Spatial_Embeddings, Ready_SOTA_Embeddings, Ready_Frequency_Embeddings, Ready_Quantization_Based_Embeddings, Ready_Spread_Spectrum_Embeddings